{
  "kind": "plugin",
  "type": "step",
  "name": "ecr",
  "spec": {
    "name": "AWS ECR",
    "description": "The ECR plugin can be used to build and publish images to the Amazon ECR registry.",
    "step": {
      "type": "script",
      "spec": {
        "image": "plugins/ecr",
        "envs": {
          "PLUGIN_ACCESS_KEY": "${{ inputs.access_key }}",
          "PLUGIN_AUTH": "${{ inputs.auth }}",
          "PLUGIN_BIP": "${{ inputs.bip }}",
          "PLUGIN_BUILD_ARGS": "${{ inputs.build_args }}",
          "PLUGIN_CONTEXT": "${{ inputs.context }}",
          "PLUGIN_CREATE_REPOSITORY": "${{ inputs.create_repository }}",
          "PLUGIN_CUSTOM_DNS": "${{ inputs.custom_dns }}",
          "PLUGIN_DOCKERFILE": "${{ inputs.dockerfile }}",
          "PLUGIN_FORCE_TAG": "${{ inputs.force_tag }}",
          "PLUGIN_INSECURE": "${{ inputs.insecure }}",
          "PLUGIN_LIFECYCLE_POLICY": "${{ inputs.lifecycle_policy }}",
          "PLUGIN_MIRROR": "${{ inputs.mirror }}",
          "PLUGIN_REGION": "${{ inputs.region }}",
          "PLUGIN_REPO": "${{ inputs.repo }}",
          "PLUGIN_REPOSITORY_POLICY": "${{ inputs.repository_policy }}",
          "PLUGIN_SCAN_ON_PUSH": "${{ inputs.scan_on_push }}",
          "PLUGIN_SECRET_KEY": "${{ inputs.secret_key }}",
          "PLUGIN_STORAGE_DRIVER": "${{ inputs.storage_driver }}",
          "PLUGIN_TAGS": "${{ inputs.tags }}"
        }
      }
    },
    "inputs": {
      "access_key": {
        "type": "string",
        "description": "AWS access key.",
        "required": true,
        "mask": true
      },
      "auth": {
        "type": "string",
        "description": "auth token for the registry.",
        "mask": true
      },
      "bip": {
        "type": "boolean",
        "description": "use for pass bridge ip.",
        "default": "false"
      },
      "build_args": {
        "type": "array",
        "description": "custom arguments passed to docker build.",
        "default": "[]"
      },
      "context": {
        "type": "string",
        "description": "context directory for the dockerfile.",
        "default": "rot of the git repo"
      },
      "create_repository": {
        "type": "boolean",
        "description": "Create repository if it does not exist.",
        "default": "false"
      },
      "custom_dns": {
        "type": "string",
        "description": "set custom dns servers for the container."
      },
      "dockerfile": {
        "type": "string",
        "description": "filename of dockerfile.",
        "default": "Dockerfile"
      },
      "force_tag": {
        "type": "boolean",
        "description": "replace existing matched image tags.",
        "default": "false"
      },
      "insecure": {
        "type": "boolean",
        "description": "enable insecure communication to this registry.",
        "default": "false"
      },
      "lifecycle_policy": {
        "type": "string",
        "description": "filename of ecr lifecycle json policy."
      },
      "mirror": {
        "type": "string",
        "description": "use a mirror registry instead of pulling images directly from the central Hub."
      },
      "region": {
        "type": "string",
        "description": "AWS region.",
        "default": "us-east-1"
      },
      "repo": {
        "type": "string",
        "description": "repository name for the image.",
        "required": true
      },
      "repository_policy": {
        "type": "string",
        "description": "filename of ecr repository json policy."
      },
      "scan_on_push": {
        "type": "boolean",
        "description": "boolean of whether to enable automatic ECR images vulnerabilities scanning for repository if it was created with create_repository=true.",
        "default": "false"
      },
      "secret_key": {
        "type": "string",
        "description": "AWS secret key.",
        "required": true,
        "mask": true
      },
      "storage_driver": {
        "type": "string",
        "description": "supports aufs, overlay or vfs drivers."
      },
      "tags": {
        "type": "array",
        "description": "repository tag for the image, defaults to latest.",
        "default": "latest"
      }
    }
  }
}
