{
  "kind": "plugin",
  "type": "step",
  "name": "java-maven",
  "spec": {
    "name": "Java Maven",
    "description": "The Java Apache Maven plugin that can be used to build Java applications using Apache Maven build tool.",
    "step": {
      "type": "script",
      "spec": {
        "image": "https://hub.docker.com/repository/docker/kameshsampath/drone-java-maven-plugin",
        "envs": {
          "PLUGIN_CONTEXT_DIR": "${{ inputs.context_dir }}",
          "PLUGIN_GOALS": "${{ inputs.goals }}",
          "PLUGIN_MAVEN_MIRROR_URL": "${{ inputs.maven_mirror_url }}",
          "PLUGIN_MAVEN_MODULES": "${{ inputs.maven_modules }}",
          "PLUGIN_PROXY_HOST": "${{ inputs.proxy_host }}",
          "PLUGIN_PROXY_NON_PROXY_HOSTS": "${{ inputs.proxy_non_proxy_hosts }}",
          "PLUGIN_PROXY_PASSWORD": "${{ inputs.proxy_password }}",
          "PLUGIN_PROXY_PORT": "${{ inputs.proxy_port }}",
          "PLUGIN_PROXY_PROTOCOL": "${{ inputs.proxy_protocol }}",
          "PLUGIN_PROXY_USER": "${{ inputs.proxy_user }}",
          "PLUGIN_SERVER_PASSWORD": "${{ inputs.server_password }}",
          "PLUGIN_SERVER_USER": "${{ inputs.server_user }}"
        }
      }
    },
    "inputs": {
      "context_dir": {
        "type": "string",
        "description": "The context directory within the source repository where \"pom.xml\" is found to execute the maven goals. Defaults to Drone workspace root."
      },
      "goals": {
        "type": "array",
        "description": "An array of maven goals to run.",
        "default": "-DskipTests clean install"
      },
      "maven_mirror_url": {
        "type": "string",
        "description": "The maven mirror to use for downloading the build dependencies."
      },
      "maven_modules": {
        "type": "array",
        "description": "An array of maven modules to be built incase of a multi module maven project."
      },
      "proxy_host": {
        "type": "string",
        "description": "Proxy server Host.",
        "default": "false"
      },
      "proxy_non_proxy_hosts": {
        "type": "array",
        "description": "Non proxy server hosts.",
        "default": "false"
      },
      "proxy_password": {
        "type": "string",
        "description": "The password for the proxy server.",
        "mask": true
      },
      "proxy_port": {
        "type": "number",
        "description": "Port number for the proxy server."
      },
      "proxy_protocol": {
        "type": "string",
        "description": "Protocol for the proxy ie http or https.",
        "default": "false"
      },
      "proxy_user": {
        "type": "string",
        "description": "The username for the proxy server.",
        "mask": true
      },
      "server_password": {
        "type": "string",
        "description": "The password for the maven repository manager server.",
        "mask": true
      },
      "server_user": {
        "type": "string",
        "description": "The username for the maven repository manager server."
      }
    }
  }
}
