{
  "kind": "plugin",
  "type": "step",
  "name": "marathon",
  "spec": {
    "name": "Marathon",
    "description": "This plugin can be used to deploy applications to a Marathon server.",
    "step": {
      "type": "script",
      "spec": {
        "image": "e20co/drone-marathon",
        "envs": {
          "PLUGIN_MARATHONFILE": "${{ inputs.marathonfile }}",
          "PLUGIN_SERVER": "${{ inputs.server }}",
          "PLUGIN_TRIGGER_RESTART": "${{ inputs.trigger_restart }}",
          "PLUGIN_VALUES": "${{ inputs.values }}"
        }
      }
    },
    "inputs": {
      "marathonfile": {
        "type": "string",
        "description": "The Marathon configuration file.",
        "default": "marathon.json"
      },
      "server": {
        "type": "string",
        "description": "Marathon server URL.",
        "default": "http://marathon.mesos:8080"
      },
      "trigger_restart": {
        "type": "boolean",
        "description": "Force a restart of the application.",
        "default": "false"
      },
      "values": {
        "type": "object",
        "description": "Map of values to replace in the marathonfile."
      }
    }
  }
}
