{
  "kind": "plugin",
  "type": "step",
  "name": "cloudformation",
  "spec": {
    "name": "AWS CloudFormation",
    "description": "The CloudFormation plugin can be used to create/update or delete stacks, and to validate templates.",
    "step": {
      "type": "script",
      "spec": {
        "image": "robertstettner/drone-cloudformation",
        "envs": {
          "PLUGIN_ACCESS_KEY": "${{ inputs.access_key }}",
          "PLUGIN_BATCH": "${{ inputs.batch }}",
          "PLUGIN_MODE": "${{ inputs.mode }}",
          "PLUGIN_PARALLEL": "${{ inputs.parallel }}",
          "PLUGIN_PARAMS": "${{ inputs.params }}",
          "PLUGIN_REGION": "${{ inputs.region }}",
          "PLUGIN_SECRET_KEY": "${{ inputs.secret_key }}",
          "PLUGIN_STACKNAME": "${{ inputs.stackname }}",
          "PLUGIN_TEMPLATE": "${{ inputs.template }}"
        }
      }
    },
    "inputs": {
      "access_key": {
        "type": "string",
        "description": "the AWS access key.",
        "mask": true
      },
      "batch": {
        "type": "array",
        "description": "an array of configurations."
      },
      "mode": {
        "type": "string",
        "description": "Mode to run the plugin, options are createOrUpdate, create, delete, validate.",
        "default": "createOrUpdate"
      },
      "parallel": {
        "type": "boolean",
        "description": "whether to run the batch in parallel.",
        "default": "false"
      },
      "params": {
        "type": "object",
        "description": "object of parameters to feed into the template. Not needed for validate and delete modes."
      },
      "region": {
        "type": "string",
        "description": "the AWS region to deploy to.",
        "default": "eu-west-1"
      },
      "secret_key": {
        "type": "string",
        "description": "the AWS secret key.",
        "mask": true
      },
      "stackname": {
        "type": "string",
        "description": "the name of the CloudFormation stack. Required for all but validate mode."
      },
      "template": {
        "type": "string",
        "description": "the path to the CloudFormation template. Required for all but delete mode."
      }
    }
  }
}
