{
  "kind": "plugin",
  "type": "step",
  "name": "webhook",
  "spec": {
    "name": "Webhook",
    "description": "Use the Webhook plugin to notify services via Webhook when a build completes. You will need to supply Drone with outgoing Webhook URLs.",
    "step": {
      "type": "script",
      "spec": {
        "image": "plugins/webhook",
        "envs": {
          "PLUGIN_CONTENT_TYPE": "${{ inputs.content_type }}",
          "PLUGIN_DEBUG": "${{ inputs.debug }}",
          "PLUGIN_HEADERS": "${{ inputs.headers }}",
          "PLUGIN_METHOD": "${{ inputs.method }}",
          "PLUGIN_PASSWORD": "${{ inputs.password }}",
          "PLUGIN_SKIP_VERIFY": "${{ inputs.skip_verify }}",
          "PLUGIN_TEMPLATE": "${{ inputs.template }}",
          "PLUGIN_URLS": "${{ inputs.urls }}",
          "PLUGIN_USERNAME": "${{ inputs.username }}"
        }
      }
    },
    "inputs": {
      "content_type": {
        "type": "string",
        "description": "The content type of the webhook.",
        "default": "application/json"
      },
      "debug": {
        "type": "boolean",
        "description": "Enable debug information.",
        "default": "false"
      },
      "headers": {
        "type": "array",
        "description": "Map of custom headers"
      },
      "method": {
        "type": "string",
        "description": "The HTTP method to use for the request.",
        "default": "POST"
      },
      "password": {
        "type": "string",
        "description": "The password to use for basic auth.",
        "mask": true
      },
      "skip_verify": {
        "type": "boolean",
        "description": "Skip SSL verification.",
        "default": "false"
      },
      "template": {
        "type": "string",
        "description": "Custom template for webhook"
      },
      "urls": {
        "type": "string",
        "description": "The URLs to send the webhook to.",
        "required": true
      },
      "username": {
        "type": "string",
        "description": "The username to use for basic auth."
      }
    }
  }
}
