{
  "kind": "plugin",
  "type": "step",
  "name": "coveralls",
  "spec": {
    "name": "Coveralls",
    "description": "This plugin can upload coverage reports to Coveralls.",
    "step": {
      "type": "script",
      "spec": {
        "image": "lizheming/drone-coveralls",
        "envs": {
          "PLUGIN_DEBUG": "${{ inputs.debug }}",
          "PLUGIN_FILES": "${{ inputs.files }}",
          "PLUGIN_TOKEN": "${{ inputs.token }}"
        }
      }
    },
    "inputs": {
      "debug": {
        "type": "boolean",
        "description": "if you want to debug, set it to true.",
        "default": "false"
      },
      "files": {
        "type": "array",
        "description": "List of files to upload.",
        "required": true
      },
      "token": {
        "type": "string",
        "description": "if you have not set environment COVERALLS_REPO_TOKEN, you should set the private repository token.",
        "mask": true
      }
    }
  }
}
