{
  "kind": "plugin",
  "type": "step",
  "name": "gpgsign",
  "spec": {
    "name": "GPG Sign",
    "description": "This plugin can sign your artifacts and build results with [GnuPG](https://www.gnupg.org/).",
    "step": {
      "type": "script",
      "spec": {
        "image": "plugins/gpgsign",
        "envs": {
          "PLUGIN_CLEAR_SIGN": "${{ inputs.clear_sign }}",
          "PLUGIN_DETACH_SIGN": "${{ inputs.detach_sign }}",
          "PLUGIN_EXCLUDES": "${{ inputs.excludes }}",
          "PLUGIN_FILES": "${{ inputs.files }}",
          "PLUGIN_KEY": "${{ inputs.key }}",
          "PLUGIN_PASSPHRASE": "${{ inputs.passphrase }}"
        }
      }
    },
    "inputs": {
      "clear_sign": {
        "type": "boolean",
        "description": "Generate a clear-sign signature.",
        "default": "false"
      },
      "detach_sign": {
        "type": "boolean",
        "description": "Generate a detach-sign signature.",
        "default": "false"
      },
      "excludes": {
        "type": "array",
        "description": "List of globs to exclude files.",
        "default": "[]"
      },
      "files": {
        "type": "array",
        "description": "List of globs to match files.",
        "default": "[]",
        "required": true
      },
      "key": {
        "type": "string",
        "description": "Private GnuPG key, optionally base64 encoded.",
        "required": true,
        "mask": true
      },
      "passphrase": {
        "type": "string",
        "description": "passphrase for the private key.",
        "required": true,
        "mask": true
      }
    }
  }
}
