{
  "kind": "plugin",
  "type": "step",
  "name": "github-release",
  "spec": {
    "name": "Github Release",
    "description": "The github-release plugin is used to publish files and artifacts to GitHub Release.",
    "step": {
      "type": "script",
      "spec": {
        "image": "plugins/github-release",
        "envs": {
          "PLUGIN_API_KEY": "${{ inputs.api_key }}",
          "PLUGIN_BASE_URL": "${{ inputs.base_url }}",
          "PLUGIN_CHECKSUM": "${{ inputs.checksum }}",
          "PLUGIN_DRAFT": "${{ inputs.draft }}",
          "PLUGIN_FILES": "${{ inputs.files }}",
          "PLUGIN_FILE_EXISTS": "${{ inputs.file_exists }}",
          "PLUGIN_NOTE": "${{ inputs.note }}",
          "PLUGIN_OVERWRITE": "${{ inputs.overwrite }}",
          "PLUGIN_PRERELEASE": "${{ inputs.prerelease }}",
          "PLUGIN_TITLE": "${{ inputs.title }}",
          "PLUGIN_UPLOAD_URL": "${{ inputs.upload_url }}"
        }
      }
    },
    "inputs": {
      "api_key": {
        "type": "string",
        "description": "GitHub oauth token with public_repo or repo permission. If you create your token, ensure you select the correct scope. For private repositories you have to select repo while public repositories only requires public_repo.",
        "required": true
      },
      "base_url": {
        "type": "string",
        "description": "GitHub base URL, only required for GHE"
      },
      "checksum": {
        "type": "string",
        "description": "checksum takes hash methods to include in your GitHub release for the files specified. Supported hash methods include - md5, sha1, sha256, sha512, adler32, and crc32."
      },
      "draft": {
        "type": "boolean",
        "description": "create a draft release",
        "default": "false"
      },
      "file_exists": {
        "type": "string",
        "description": "what to do if an file asset already exists, supported values - overwrite, skip and fail.",
        "default": "overwrite"
      },
      "files": {
        "type": "array",
        "description": "files to upload to GitHub Release, globs are allowed",
        "required": true
      },
      "note": {
        "type": "string",
        "description": "file or string with notes for the release"
      },
      "overwrite": {
        "type": "boolean",
        "description": "force overwrite existing release informations (only title and note)",
        "default": "false"
      },
      "prerelease": {
        "type": "boolean",
        "description": "create a pre-release",
        "default": "false"
      },
      "title": {
        "type": "string",
        "description": "file or string for the title shown in the gitea release",
        "required": true
      },
      "upload_url": {
        "type": "string",
        "description": "GitHub upload URL, only required for GHE"
      }
    }
  }
}
